name: Actualizar KML Copernicus

on:
  workflow_dispatch:

jobs:
  generar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Ejecutar script
        run: python generar_kml.py
